name: Integration Test PHP

on:
  push:
    # Only run if PHP-related files changed.
    paths:
      - '**.php'
      - 'phpunit.integration.xml.dist'
      - 'composer.json'
      - 'composer.lock'
      - 'tests/phpunit/**'
      - '.github/workflows/integration-test-php.yml'
    branches:
      - main
  pull_request:
    # Only run if PHP-related files changed.
    paths:
      - '**.php'
      - 'phpunit.integration.xml.dist'
      - 'composer.json'
      - 'composer.lock'
      - 'tests/phpunit/**'
      - '.github/workflows/integration-test-php.yml'

jobs:
  test:
    name: 'Integration Test PHP ${{ matrix.php }} - WP ${{ matrix.wp }}'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 9306:3306
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_ROOT_PASSWORD: password
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      matrix:
        php: ['7.4', '7.0']
        wp: ['latest', '5.2', '4.9.6']
        include:
          - php: '8.0'
            wp: 'latest'

    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mysql
          tools: composer

      - name: Setup WordPress
        run: |
          if [[ "${{ matrix.wp }}" == "latest" ]]; then
            curl -s http://api.wordpress.org/core/version-check/1.7/ > /tmp/wp-latest.json
            WP_VERSION=$(grep -o '"version":"[^"]*' /tmp/wp-latest.json | sed 's/"version":"//')
          else
            WP_VERSION="${{ matrix.wp }}"
          fi
          composer require "roots/wordpress:$WP_VERSION" "wp-phpunit/wp-phpunit:$WP_VERSION" --dev --no-update

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup Composer cache
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-wp$WP_VERSION
          restore-keys: |
            ${{ runner.os }}-composer-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-suggest --no-progress --no-interaction --no-scripts
          composer update roots/wordpress wp-phpunit/wp-phpunit

      - name: Shutdown default MySQL service
        run: sudo service mysql stop

      - name: Run tests
        run: composer test-integration