name: Lint PHP

on:
  push:
    # Only run if PHP-related files changed.
    paths:
      - '**.php'
      - 'phpcs.xml.dist'
      - 'phpmd.xml.dist'
      - 'composer.json'
      - 'composer.lock'
      - '.github/workflows/lint-php.yml'
    branches:
      - main
  pull_request:
    # Only run if PHP-related files changed.
    paths:
      - '**.php'
      - 'phpcs.xml.dist'
      - 'phpmd.xml.dist'
      - 'composer.json'
      - 'composer.lock'
      - '.github/workflows/lint-php.yml'

jobs:
  lint:
    name: Lint PHP
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup Composer cache
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
            ${{ runner.os }}-

      - name: Validate composer.json
        run: composer --no-interaction validate --no-check-all

      - name: Install dependencies
        run: composer install --prefer-dist --no-suggest --no-progress --no-interaction

      - name: Detect coding standard violations (PHPCS)
        run: composer lint

      - name: Static Analysis (PHPMD)
        run: composer analyze